# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Demo  # Correct self-hosted agent pool name

variables:
  buildConfiguration: 'Release'

steps:
# Step 1: Build the solution
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

# Step 2: Run tests (this will include Selenium C# tests)
- script: dotnet test --configuration $(buildConfiguration)
  displayName: 'dotnet test $(buildConfiguration)'